### ISSUE TITLE
[Suggestion] Hide update link for non wp.org plugins

### ISSUE THREAD

**Issue by pedro-mendonca** [mayukojpn/force-update-translations#10]
A premium or private plugin isn't available in translate.wp.org, so clicking on the update link will always be a dead end.

A first option might be to just check if the plugin exists in the wp.org and only show the *Update Translation* if the plugin exists in the directory.

A second option, might be an option to add a particular link to a GitHub or custom/premium repo, as it happens in the settings of GP Auto Extract plugin.

**Comment by mayukojpn** [comment]
Thank you very much for great idea and patch! I'll apply your patch to next update :)

I also like second option. Let's continue working on it independently #12
