### ISSUE TITLE
Add Themes support

### ISSUE THREAD

**Issue by pedro-mendonca** [mayukojpn/force-update-translations#15]
The *Update translation* link might be added to the network themes list - hooked in [theme_action_links](https://developer.wordpress.org/reference/hooks/theme_action_links).

For single site I didn't found any other _action links_ hook, also can't think of a good place to insert the link, other than the theme details page.

**Comment by Dartui** [comment]
What you think about this? AFAIK this is the best what we can do. There are no actions nor filters to modify JavaScript templates which are used on themes page.

To achieve this I used `wp_prepare_themes_for_js` and modified `description` parameter. Something like this:
```php
add_filter('wp_prepare_themes_for_js', function ($themes) {
    foreach ($themes as &$theme) {
        // we need to close description paragraph
        $theme['description'] .= '</p>';
        // we can omit closing paragraph tag
        $theme['description'] .= '<p class="theme-update-translation"><a href="#">Update translation</a>';
    }

    return $themes;
});
```

![obraz](https://user-images.githubusercontent.com/2657856/46260771-80f91900-c4ea-11e8-94bf-2661efd795f7.png)

**Comment by mayukojpn** [comment]
@Dartui I'm sorry for delay to check! And thank you for suggesting code ❤️❤️❤️

Can you send me a pull request if I make `add-theme-support` branch? Then I'll add a generated link to GlotPress :)

Update: I added a branch 😉
https://github.com/mayukojpn/force-update-translations/tree/add-theme-support

**Comment by pedro-mendonca** [comment]
I've opened a ticket in core to add a few useful hooks on themes.php page.
https://core.trac.wordpress.org/ticket/47650

![imagem](https://user-images.githubusercontent.com/7371591/60679695-7c4e0080-9e80-11e9-952c-83b9b7baa449.png)

If accepted, will allow to add action buttons and aditional info on the theme details panel.

If it's not accepted, than we can do the way @Dartui suggested above to include some more `<p>` in the theme description.
