### ISSUE TITLE
Needs plugin icon

### ISSUE THREAD

**Issue by mayukojpn** [mayukojpn/force-update-translations#17]
Having [plugin icon](https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#plugin-icons) would be nice!

Ideas:
https://wordpress.org/plugins/browse/beta/

**Comment by pedro-mendonca** [comment]
Like the plugin icons in the Updates page?

**Comment by mayukojpn** [comment]
Exactly!

**Comment by pedro-mendonca** [comment]
~Won't it make the plugin unnecessarily heavy?~ [edited]
Forget this, I misunderstood this.
Great idea 👍

**Comment by mayukojpn** [comment]
Let me make the asset branch :)

**Comment by mayukojpn** [comment]
Thanks @mekemoke for the cool icon! Related: #18
