### ISSUE TITLE
Replace the term "Exported" with a more proper one.

### ISSUE THREAD

**Issue by mayukojpn** [mayukojpn/force-update-translations#33]
@nekojonez suggested on [WP forum](https://wordpress.org/support/topic/exported/) that the term "exported" is not fit for this situation.

https://github.com/mayukojpn/force-update-translations/blob/faff4b8164754bab7d8fe85e699a1318d9db5b14/force-update-translations.php#L45

"Downloaded" would fit in this string instead.

**Comment by NekoJonez** [comment]
Created a patch and did a pull request ;) I hope I did it right since this is my first time :o
