### ISSUE TITLE
Child theme support.

### ISSUE THREAD

**Issue by mayukojpn** [mayukojpn/force-update-translations#35]
In most cases of trying to update the translation files of child themes, it intends to get the parent themes' one since this plugin is for translation.wordpress.org.

**Comment by genepine** [comment]
Hello
I made Child Theme by  Child Theme Configurator. 
After activating the child theme, when I go to Appearance > Update Translations, I get the following error:

```
Cannot get source file: https://translate.wordpress.org/projects/wp-themes//ja/default/export-translations?filters%5Bstatus%5D=current_or_waiting_or_fuzzy

Cannot get source file: https://translate.wordpress.org/projects/wp-themes//ja/default/export-translations?filters%5Bstatus%5D=current_or_waiting_or_fuzzy&format=mo
```

`wp-themes//ja`
cannot get the child theme name.

**Comment by mayukojpn** [comment]
@genepine Hi! Thanks for the heads up.
I like the idea! That makes sense to check if the theme has a parent.
I'll check if I have time to work on that.

**Comment by pedro-mendonca** [comment]
There are child themes in wp.org, I think the procedure should be:
1) Try to get the translation if the theme is on wp.org
2) Check if it's a child theme, if so, also try to get its parent theme translation, if it exists on wp.org
