### ISSUE TITLE
Glotpress locale is different from WordPress locale

### ISSUE THREAD

**Issue by Dartui** [mayukojpn/force-update-translations#4]
Hi, let's take Gutenberg plugin and Polish locale as an example.

If we change `$locale` variable in plugin to `pl`, we will have this URL to download translation:
```
https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/pl/default/export-translations?filters[status]=current_or_waiting_or_fuzzy&format=mo
```
This is totally correct, but will store it into `gutenberg-pl.mo` file. WordPress will not recognize it, because for Polish language the locale slug is `pl_PL`.

There are also another languages, which has two "segments" in locale. On GlotPress there are separated with dash, but WordPress requires underscore as separator (`en-gb` vs `en_GB`)

**Comment by mayukojpn** [comment]
Hi! @Dartui Thank you for reporting! And I'm sorry for forgetting about locale switcher!

I wrote a code for switching locale by user setting, and will dig more into pairing of different WordPress locale codes.

**Comment by mayukojpn** [comment]
@Dartui It looks this ☝️ change also fixed 2 type locale code problem as well. I'll update a plugin on wordpress.org shortly, so please test it on your site :)

**Comment by mayukojpn** [comment]
Oops now I understand the problem, wait a moment!

**Comment by mayukojpn** [comment]
@Dartui It works now :) Can you test on your site? Thanks!

**Comment by Dartui** [comment]
@mayukojpn everything works great, thanks a lot!
