### ISSUE TITLE
Cannot get source file problem

### ISSUE THREAD

**Issue by anyapas** [mayukojpn/force-update-translations#40]
It shows these 2 error messages:

> Cannot get source file: https://translate.wordpress.org/projects/wp-themes/plant/en/default/export-translations?filters%5Bstatus%5D=current_or_waiting_or_fuzzy
> 
> Cannot get source file: https://translate.wordpress.org/projects/wp-themes/plant/en/default/export-translations?filters%5Bstatus%5D=current_or_waiting_or_fuzzy&format=mo

please help :'(

**Comment by Dartui** [comment]
There is no theme in WordPress repository with `plant` slug: https://wordpress.org/themes/plant/. From where did you get this theme?

**Comment by anyapas** [comment]
I purchased it. It's from thai developer called SeedWebs
https://th.seedwebs.com/

what is the reason of the errors?
Is it because of the theme?

**Comment by pedro-mendonca** [comment]
Force Update Translations can only get translations from the Translating WordPress repository, for free plugins and themes hosted on the repository.

**Comment by anyapas** [comment]
Thank you so much for your answer.

**Comment by pedro-mendonca** [comment]
I'll close the issue as the question is solved, but please feel free to further discuss on the subject :)
